'use client';
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useApp } from '../../context';
import AssessmentCard from '../../components/assessment-card';
export default function UserAssessments() {
    const { currentUser, navigate, startAssessment } = useApp();
    if (!currentUser)
        return null;
    return (_jsxs("div", { className: "mx-auto max-w-2xl px-4 py-6 text-center sm:px-6 sm:py-8 lg:px-8 lg:py-10", children: [_jsxs("button", { onClick: () => navigate('user-dashboard'), className: "mx-auto inline-flex items-center gap-2 text-base font-semibold mb-8 transition-colors", style: { color: '#2c7a7b' }, "aria-label": "Go back to home", children: [_jsx("svg", { className: "w-5 h-5", viewBox: "0 0 20 20", fill: "currentColor", children: _jsx("path", { fillRule: "evenodd", d: "M12.707 5.293a1 1 0 010 1.414L9.414 10l3.293 3.293a1 1 0 01-1.414 1.414l-4-4a1 1 0 010-1.414l4-4a1 1 0 011.414 0z", clipRule: "evenodd" }) }), "Back to Home"] }), _jsxs("div", { className: "mb-8", children: [_jsx("h1", { className: "text-3xl font-bold text-foreground mb-2", children: "Choose Your Assessment" }), _jsx("p", { className: "text-lg text-muted-foreground leading-relaxed", children: "Pick one of the tests below. Take your time \u2014 there is no rush. Each test takes only a minute or two, and once you start, the app will continue through all three assessments automatically." })] }), _jsxs("div", { className: "rounded-2xl p-5 mb-8 flex items-start gap-4 border text-left", style: { background: '#fffff0', borderColor: '#fefcbf' }, children: [_jsx("div", { className: "flex-shrink-0 w-10 h-10 rounded-xl flex items-center justify-center", style: { background: '#fefcbf' }, children: _jsx("svg", { className: "w-5 h-5", style: { color: '#b7791f' }, viewBox: "0 0 20 20", fill: "currentColor", children: _jsx("path", { fillRule: "evenodd", d: "M8.257 3.099c.765-1.36 2.722-1.36 3.486 0l5.58 9.92c.75 1.334-.213 2.98-1.742 2.98H4.42c-1.53 0-2.493-1.646-1.743-2.98l5.58-9.92zM11 13a1 1 0 11-2 0 1 1 0 012 0zm-1-8a1 1 0 00-1 1v3a1 1 0 002 0V6a1 1 0 00-1-1z", clipRule: "evenodd" }) }) }), _jsxs("div", { children: [_jsx("p", { className: "font-semibold text-base", style: { color: '#744210' }, children: "Before you begin" }), _jsx("p", { className: "text-base mt-1 leading-relaxed", style: { color: '#975a16' }, children: "Find a quiet place, sit comfortably, and speak clearly into your microphone. Do not worry about being perfect \u2014 just do your best." })] })] }), _jsx("div", { className: "flex flex-col gap-4", children: ['picture-recall', 'animal-naming', 'structured-speech'].map(type => (_jsx(AssessmentCard, { type: type, onStart: startAssessment }, type))) })] }));
}
