# ===================================================================
# DEMENTAI CLINICAL MICROSERVICE DATABASE & ML CONFIGURATION
# ===================================================================
db.driver=com.mysql.cj.jdbc.Driver
db.url=jdbc:mysql://localhost:3306/dementai_auth_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
db.username=root
db.password=Nikhil!

# Gmail SMTP Dispatch Credentials
mail.smtp.host=smtp.gmail.com
mail.smtp.port=587
mail.sender.email=nikhil.s.scorpio@gmail.com
mail.sender.password=Nikhil1102

# URL of Service 3 (Python ML Microservice on Port 8000)
ml.service.url=http://localhost:8000

# Shared JWT Secret Key for token validation
jwt.secret=DementAI_SuperSecret_JWT_Key_2026_Microservices_Auth_Token_12345
